Subscription stream InventoryChanged update
mdingena/att-client pull request #5
Opened 2023-06-11 17:46 UTC by NCferrieri

Edited files
- att-client\dist\types\ServerConnection\SubscriptionEventMessage.d.ts
- att-client\dist\types\ServerConnection\SubscriptionEvent.d.ts

2023-06-11 18:31 UTC, PolyphonyRequiem commented on src/ServerConnection/SubscriptionEvent.ts
> +export type SubscriptionEvent = 'DebugLog' | 'ErrorLog' | 'FatalLog' | 'InfoLog' | 'InventoryChanged' | 'ObjectKilled' | 'PlayerJoined' | 'PlayerKilled' | 'PlayerLeft' | 'PlayerMovedChunk' | 'PlayerS
well this isn't going to fly, switch the style back.

2023-06-11 18:31 UTC, PolyphonyRequiem commented on src/ServerConnection/SubscriptionEventMessage.ts
> -
nor this, not the style

2023-06-11 18:32 UTC, PolyphonyRequiem commented on src/ServerConnection/SubscriptionEventMessage.ts
> +    eventType: 'DebugLog';
why change indentation?  probably a different IDE setting.

2023-06-11 18:34 UTC, PolyphonyRequiem commented on src/ServerConnection/SubscriptionEventMessage.ts
> +        changetype: string,
use the union model or whatever TS calls it, like below.

source: 'Unknown' | 'Impact' | 'FallDamage';

2023-06-12 02:19 UTC, mdingena commented
@NCferrieri Can you please run `npm installl` followed by `npm run prepare` to ensure you have Husky installed? It enforces a pre-commit hook that will make sure the code you will be committing gets formatted like everything else. It's how I configured my code quality and style and I won't accept pull requests that use different code styles, such as different indentation, line lengths, mixed quote usage, semi-colon usage, etc.

If you install Husky you don't need to even think about it. Just commit your code and it will format your code before committing.

2023-06-12 02:26 UTC, mdingena requested changes
It's difficult to tell what you really changed because your IDE changed lots of unrelated things such as indentation. Please enforce the project's code style using ESLint and Prettier.

2023-06-13 15:21 UTC, TheRavenSeb commented
Understood we'll fix that together @NCferrieri

2023-06-19 02:14 UTC, mdingena approved these changes
Thanks for your contribution. :)

2023-06-19 02:14 UTC, merged